repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: check-json
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11
        args: ['--line-length=100']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']

  - repo: local
    hooks:
      - id: pytest-fast
        name: pytest-fast
        entry: bash -c 'source venv/bin/activate && pytest -x -m "not slow" --tb=short'
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]

      - id: check-requirements
        name: check-requirements
        entry: bash -c 'pip check'
        language: system
        pass_filenames: false
        always_run: false
        stages: [commit]
