# Cloudflare Tunnel Configuration for Agentic RAG API
# This configuration securely exposes only the n8n endpoints

tunnel: YOUR-TUNNEL-UUID-HERE
credentials-file: /path/to/your/tunnel/credentials.json

# Ingress rules - ONLY expose n8n endpoints
ingress:
  # n8n chat endpoint - main integration point
  - hostname: rag-api.yourdomain.com
    path: /n8n/*
    service: http://127.0.0.1:8058
    originRequest:
      httpHostHeader: rag-api.yourdomain.com
      # Security headers
      originServerName: rag-api.yourdomain.com
      noTLSVerify: false
      # Timeout settings
      connectTimeout: 30s
      tlsTimeout: 10s
      tcpKeepAlive: 30s
      keepAliveConnections: 10
      keepAliveTimeout: 90s

  # Health check endpoint (optional, for monitoring)
  - hostname: rag-api.yourdomain.com
    path: /health
    service: http://127.0.0.1:8058
    originRequest:
      httpHostHeader: rag-api.yourdomain.com

  # Block all other paths - return 404
  - service: http_status:404

# Tunnel-level configuration
warp-routing:
  enabled: false

# Logging
logLevel: info
logFile: /var/log/cloudflared/tunnel.log

# Metrics (optional)
metrics: 0.0.0.0:8080

# Connection settings
retries: 3
grace-period: 30s